### ISSUE TITLE
Latest elegant.Accordion.js not working

### ISSUE THREAD

**Issue by ghost** [ProLoser/ElegantAccordion#6]
I just download the latest elegant.Accordion.js , and is not working.... 

so I needed to return to the previous version .... but the problem with the previous version is that AutoPlay doesn't work..... I mean, the autoplay can't be turned off!

the problem on the new js is: " $page.find("*").switchClass is not a function "

hope this issue could be check ....

thanks

**Comment by ProLoser** [comment]
Hmm I didn't realize I tweaked the requirements. switchClass() is found in jquery ui.

If this is a problem, I can make a branched version that doesn't rely on ui, but this sort of goes back to the bulkier hard-coded approach.

**Comment by ghost** [comment]
Hey Thanks for the fast Response..

I already tried with jQuery 1.6.1 and jUI 1.8.14, and well here is the sample in what is happening

http://jsfiddle.net/SaPc3/

thanks really very much...

**Comment by ProLoser** [comment]
http://jsfiddle.net/SaPc3/1/

You made the div display: none, and put display: block; on bgGradient, but that's actually a secondary div that's added to allow the white background to slide in from the bottom without sliding the description. Frankly I'm not happy at all with how the animation is handled. The efficient flag needs to be dropped and the whole thing should be more efficient by default. The reason why when you hover you get a subtle (millisecond) delay is because of the find('*').addClass('active') which is kinda... crappy.

Problem is you can't do css class animations to children. AKA: `div.active {}` css will animate but `div.active h2 {}` css won't animate.

**Comment by ghost** [comment]
Thanks for point me in the correct way , I add the new commit and everything is working perfect.!

I really wanted to do something and help but I'm just a CSS guy not that great in jQuery hehehe.

Thanks very much again....
